rdkcentral/MVT

- README.md
- anyplayer/index.html
- patches/0001_js_mse_eme_mvt.patch
- src/engines.js
- src/main.js
Add new debug flag for mse players
> Add debug flag for mse players

- CHANGELOG.md
- README.md
- index.html
- src/main.js
- style.css
- Add new file `CHANGELOG.md`.
- Add MVT version info on the UI in the bottom right corner.
- Add info about versioning to the README.
> Add MVT versioning and CHANGELOG

- patches/0002_js_mse_eme_mvt_AudioTagChangeFor_FMP4_FMP3_stream.patch
- prepare_submodule.sh
added patch which replaced video tag with audio tag for all fmp4_mp3 tests
> Replaced video tag with audio tag for all fmp4_mp3 tests

- CHANGELOG.md
- src/main.js
Replaced video tag with audio tag for all fmp4_mp3 tests
> Release v2.12.0

- README.md
- src/suites.js
Enabled fix rate for all test suites.
> Enabled Fix Rate tests

- CHANGELOG.md
- src/main.js
Updating release version to 2.13.0
> Release v2.13.0

- src/engines.js
Timeout value was changed from 2000 to 6000
> Change timeout value to 6000

- patches/0003_js_mse_eme_mvt_Add_HtmlTests.patch
- prepare_submodule.sh
Added Html tests for verification of Html features support
> Add Html tests

- patches/0004_js_mse_eme_mvt_Add_CSSTests.patch
- prepare_submodule.sh
Added CSS tests for verification of CSS modules support
> Add CSS tests

- CHANGELOG.md
- src/main.js
Updated release version to v2.14.0
> Release v2.14.0

- patches/0005_js_mse_eme_mvt_Add_JSTests.patch
- prepare_submodule.sh
> Add JavaScript Tests

- patches/0006_js_mse_eme_mvt_Add_WPTTests.patch
- prepare_submodule.sh
> Add WPT tests

- CHANGELOG.md
- src/main.js
> Release v2.15.0

- docker_run.sh
- download-test-materials.sh
- httpd.conf
- patches/0007_js_mse_eme_mvt_Add_Browse_and_Download_Media_Assets.patch
- prepare_submodule.sh
Add browse and download media assets tabs
> Add browse and download media assets tabs

- CHANGELOG.md
- src/main.js
> Release v2.16.0

- src/constants.js
- src/suites.js
Add tests for verification of Quicktime container
> Add QuickTime container check

- CHANGELOG.md
- src/main.js
> Release v2.17.0

- src/mediaStreams.js
include PR CENC test, as described in the test:
https://wikiprojects.upc.biz/display/CTOM/WPE2.22+-+testing#:~:text=is%20playing%20smoothly-,Playready%20CENC,-open%20%22Euronews%20application
> ONEMTEST-75623 adding PlayReady CENC test

- fonts.html
- patches/0009_js_mse_eme_mvt_Add_system_fonts_check.patch
- prepare_submodule.sh
> Add System Fonts Check

- CHANGELOG.md
- src/main.js
> Release v2.18.0

- src/mediaStreams.js
- src/mediaTests.js
- src/suites.js
Add performance test (time taken for video to start and compare it with threshold value of 4 secs) in each test suite
> Add performance test

- platform/config.json
- src/main.js
- src/mvtWsClient.js
Description: Adding WS client for processing commands from MVT runner
> ONEM-27298: Added support for WS client in MVT

- CHANGELOG.md
- src/main.js
> Release v2.19.0

- src/mvtWsClient.js
Changing WebSocket communication b/w MVT and MVT Runner to WebSocket secure.
> ONEM-27298: Updating communication to MVT-runner to WSS

- CHANGELOG.md
- src/main.js
> Release v2.20.0
